import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [  
  // Admin Modules
  {
    path: "/admin/dashboard",
    title: "Dashboard",
    moduleName: "admin",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["admin"],
    submenu: [],
  },
  
  {
    path: "",
    title: "General Masters",
    moduleName: "generalmasters",
    iconType: "feather",
    icon: "monitor",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["admin"],
    submenu: [
      {
        path: "/admin/states",
        title: "States",
        moduleName: "state",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["admin"],
        submenu: [],
      }, {
        path: "/admin/cities",
        title: "Cities",
        moduleName: "cities",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["admin"],
        submenu: [],
      }, {
        path: "/admin/pincodes",
        title: "Pincodes",
        moduleName: "pincodes",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["admin"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Business Masters",
    moduleName: "businessmasters",
    iconType: "feather",
    icon: "monitor",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["admin"],
    submenu: [
      {
        path: "/admin/admins",
        title: "Admins",
        moduleName: "admin",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["admin"],
        submenu: [],
      },
      {
        path: "/admin/vendors",
        title: "Vendors",
        moduleName: "vendor",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["admin"],
        submenu: [],
      }, {
        path: "/admin/businesses",
        title: "Businesses",
        moduleName: "businesses",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["admin"],
        submenu: [],
      },
      {
        path: "/admin/productcategories",
        title: "Product Categories",
        moduleName: "productcategories",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["admin"],
        submenu: [],
      },
    ],
  },

  // Vendor Modules
  {
    path: "/vendor/dashboard",
    title: "Dashboard",
    moduleName: "admin",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["vendor"],
    submenu: [],
  },
  
  {
    path: "",
    title: "Vendor Masters",
    moduleName: "generalmasters",
    iconType: "feather",
    icon: "monitor",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["vendor"],
    submenu: [
      {
        path: "/vendor/states",
        title: "States",
        moduleName: "state",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["admin"],
        submenu: [],
      }
    ],
  },

  // Business Modules
  {
    path: "/business/dashboard",
    title: "Dashboard",
    moduleName: "business",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["business"],
    submenu: [],
  },  
  {
    path: "",
    title: "Business Masters",
    moduleName: "business",
    iconType: "feather",
    icon: "monitor",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["business"],
    submenu: [
      {
        path: "/business/banners",
        title: "Banners",
        moduleName: "banner",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["business"],
        submenu: [],
      },
      {
        path: "/business/productcategories",
        title: "Product Categories",
        moduleName: "productcategory",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["business"],
        submenu: [],
      },
      {
        path: "/business/products",
        title: "Products",
        moduleName: "product",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["business"],
        submenu: [],
      }
    ],
  },
  
  {
    path: "",
    title: "Blogs Masters",
    moduleName: "blogs",
    iconType: "feather",
    icon: "monitor",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["business"],
    submenu: [
      {
        path: "/business/blogcategories",
        title: "Blog Categories",
        moduleName: "blogcategory",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["business"],
        submenu: [],
      },
      {
        path: "/business/blogs",
        title: "Blogs",
        moduleName: "blog",
        iconType: "feather",
        icon: "airplay",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["business"],
        submenu: [],
      }
    ],
  }
];
